import { PointRule, SyncState, Keyword } from '../models/index.js';

const defaultRules = [
  {
    label: 'Hasta 8 jugadores',
    minPlayers: 1,
    maxPlayers: 8,
    placingFrom: 1,
    placingTo: 1,
    points: 50,
    sortOrder: 1,
  },
  {
    label: 'Hasta 8 jugadores',
    minPlayers: 1,
    maxPlayers: 8,
    placingFrom: 2,
    placingTo: 2,
    points: 25,
    sortOrder: 2,
  },
  {
    label: 'Hasta 8 jugadores',
    minPlayers: 1,
    maxPlayers: 8,
    placingFrom: 3,
    placingTo: 4,
    points: 10,
    sortOrder: 3,
  },
  {
    label: 'Hasta 8 jugadores',
    minPlayers: 1,
    maxPlayers: 8,
    placingFrom: 5,
    placingTo: 8,
    points: 1,
    sortOrder: 4,
  },
  {
    label: 'Más de 8 jugadores',
    minPlayers: 9,
    maxPlayers: null,
    placingFrom: 1,
    placingTo: 1,
    points: 100,
    sortOrder: 5,
  },
  {
    label: 'Más de 8 jugadores',
    minPlayers: 9,
    maxPlayers: null,
    placingFrom: 2,
    placingTo: 2,
    points: 60,
    sortOrder: 6,
  },
  {
    label: 'Más de 8 jugadores',
    minPlayers: 9,
    maxPlayers: null,
    placingFrom: 3,
    placingTo: 4,
    points: 45,
    sortOrder: 7,
  },
  {
    label: 'Más de 8 jugadores',
    minPlayers: 9,
    maxPlayers: null,
    placingFrom: 5,
    placingTo: 8,
    points: 25,
    sortOrder: 8,
  },
  {
    label: 'Más de 8 jugadores',
    minPlayers: 9,
    maxPlayers: null,
    placingFrom: 9,
    placingTo: 16,
    points: 10,
    sortOrder: 9,
  },
  {
    label: 'Más de 8 jugadores',
    minPlayers: 9,
    maxPlayers: null,
    placingFrom: 17,
    placingTo: 20,
    points: 5,
    sortOrder: 10,
  },
];

const defaultKeywords = [
  {
    name: 'Blocker',
    slug: 'blocker',
    reminderText: 'Este Digimon puede bloquear en el timing de bloqueo.',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'ST1 / ST2 / ST3',
    colors: 'Todos / Negro',
    summary:
      'Keyword defensiva base del juego. Permite redirigir un ataque enemigo hacia este Digimon durante el Block Timing, siempre que pueda bloquear correctamente.',
    tips: [
      '⟨Blocker⟩ es un efecto que le da al Digimon la habilidad de bloquear, pero bloquear no es un efecto (desde BT13) ',
      'Bloquear es opcional y siempre es en el Block Timing (que viene después del Counter Timing)',
      'Para bloquear, es necesario suspender al Digimon con ⟨Blocker⟩. Si no se puede suspender, no puede bloquear ',
      'Si el Digimon con ⟨Blocker⟩ se desuspende luego de bloquear, va a poder bloquear otro ataque',
      'El mismo ataque solo puede ser bloqueado una vez. No es posible activar ⟨Blocker⟩ más de una vez por ataque, ya sea por el mismo Digimon u otro',
      'A partir de BT13, si el objetivo del ataque no va a cambiar a raíz de bloquear, no se puede declarar bloqueo y el Digimon con ⟨Blocker⟩ no se va a suspender. Esto puede pasar, por ejemplo, si el Digimon atacante es imbloqueable, irredirigible, o el Digimon con ⟨Blocker⟩ no puede bloquear o suspenderse por algún efecto, o el objetivo del ataque ya es el Digimon que quiere bloquear, o el atacante no existe más',
      'Bloquear dispara los efectos “when attack targets change” y “when a Digimon suspends” al mismo tiempo, pero no dispara los efectos “when you attack a Digimon”',
      'Es posible bloquear un ataque que se quedó sin objetivo',
      'Si un Digimon con  ⟨Blocker⟩ aparece o un Digimon gana  ⟨Blocker⟩  posteriormente a la declaración del ataque, va a poder bloquear, ya que no es un efecto que tenga trigger.',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 1,
  },
  {
    name: 'Security A. +X',
    slug: 'security-a-plus-x',
    reminderText: 'Este Digimon chequea X security adicionales.',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'ST1 / ST2',
    colors: 'Todos',
    summary:
      'Aumenta la cantidad de security checks que realiza este Digimon al atacar al jugador rival.',
    tips: [
      'Varias instancias de ⟨Security A. +X⟩ se acumulan y se suman entre sí. ',
      'Las seguridades se revelan de a una, y se activan todos los efectos que haya que activar entre un check y el siguiente.',
      'Si un Digimon gana o pierde instancias de ⟨Security A. +X⟩ durante el proceso de estar chequeando seguridades, la cantidad de seguridades restantes para chequear se actualiza en tiempo real. La cantidad restante de checks que tiene que hacer un Digimon siempre se calcula como la resta entre el Security Attack del Digimon (por defecto 1) y la cantidad de checks realizados. Es decir, si ya chequeó una seguridad y tiene ⟨Security A. +1⟩, debe chequear una más. Si al chequear la última seguridad que podía gana ⟨Security A. +1⟩, por algún efecto, debe chequear una seguridad más. Asimismo, si le faltaban chequear 2 seguridades pero pierde ⟨Security A. +1⟩ por un efecto, ya no va a chequear más. ',
      'Es obligatorio chequear la cantidad de seguridades que indique el valor de SA del Digimon, no se puede elegir chequear menos. ',
      'Si un Digimon tiene que chequear más seguridades pero no las hay, el ataque simplemente termina, no se puede ganar habiendo chequeado seguridades en el mismo ataque. ',
      'Si un Digimon tiene que chequear más seguridades de las que hay, pero el último check hace que el oponente se agregue una seguridad, va a chequear esa seguridad nueva en el mismo ataque',
      'Si un Digimon es removido de la Battle Area antes de terminar de realizar todos los checks que tenía que hacer, no va a chequear más seguridades. ',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 2,
  },
  {
    name: 'Security A. -X',
    slug: 'security-a-minus-x',
    reminderText: 'Este Digimon chequea X security menos.',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'ST3',
    colors: 'Amarillo',
    summary:
      'Reduce la cantidad de security checks que realiza este Digimon durante su ataque.',
    tips: [
      'Si un Digimon con SA 0 ataca a un jugador con seguridades, no se va a realizar ningún check y el ataque va a terminar de manera normal',
      'Si un Digimon gana o pierde instancias de ⟨Security A. -X⟩ durante el proceso de estar chequeando seguridades, la cantidad de seguridades restantes para chequear se actualiza en tiempo real, al igual que con ⟨Security A. +X⟩ ',
      'No es posible tener un valor de SA negativo. Si se intenta reducir en más que 0, simplemente queda en 0. ',
      'Si se aplican conjuntamente ⟨Security A. -X⟩ y ⟨Security A. +X⟩, el SA resultante va a ser la suma entre ellos y 1. Es decir, si un Digimon tiene ⟨Security A. -2⟩ y ⟨Security A. +3⟩, va a tener un SA de 2 y chequear 2 seguridades. ',
      'Si se aplican conjuntamente ⟨Security A. -X⟩ y ⟨Security A. +X⟩ donde X es el mismo número, el SA del Digimon no cambia en valor neto, pero el juego igualmente reconoce que el Digimon tiene aplicadas ambas keywords, para lo que concierne a efectos que se fijen eso. ',
      'Un Digimon con un valor de SA 0 no va a ganar la partida al atacar a un jugador sin seguridades. ',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 3,
  },
  {
    name: 'Recovery +X (Deck)',
    slug: 'recovery-plus-x-deck',
    reminderText: 'Colocá las X cartas superiores de tu mazo en tu security boca abajo.',
    category: 'Activa Obligatoria',
    interruptive: 'No',
    area: 'N/A',
    debut: 'ST3',
    colors: 'Amarillo',
    summary:
      'Permite recuperar security agregando cartas desde la parte superior del mazo.',
    tips: [
      'Siempre se ponen las nuevas seguridades en el tope del stack, para que sean chequeadas primeras, y siempre boca abajo sin mirarlas',
      'Si el jugador no tiene mazo al momento de activar este efecto, no pasa nada ',
      'Si el jugador está afectado por “can’t add cards to security stacks”, no pasa nada ',
      'No hay un máximo de cartas en la seguridad',
      'Si se deben agregar varias cartas porque la X era mayor a 1, se agregan de a una, para que las primeras agregadas sean las últimas en ser chequeadas ',
      '⟨Recovery +X (Deck)⟩ dispara los efectos “when cards are added to your security stack”',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 4,
  },
  {
    name: 'Piercing',
    slug: 'piercing',
    reminderText: 'Si este Digimon elimina a un Digimon rival en batalla y sobrevive, hace sus checks de security.',
    category: 'Activa Obligatoria',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT1',
    colors: 'Verde / Rojo',
    summary:
      'Hace que un ataque contra un Digimon rival también pueda convertirse en presión sobre la security si el atacante gana la batalla y sobrevive.',
    tips: [
      'El Digimon con ⟨Piercing⟩ va a realizar la misma cantidad de checks que haría si hubiera atacado al jugador (es decir, igual a su valor de SA) ',
      'Todos los efectos derivados de la batalla ([On Deletion]s) deben terminar de activarse antes que los checks puedan realizarse. Es decir, activar ⟨Piercing⟩ solo significa que el Digimon gana el derecho a realizar los checks cuando sea el momento. ',
      'Si el Digimon que activó ⟨Piercing⟩ no existe más cuando llega la fase de check, no se van a realizar los checks',
      'Si el Digimon que activó ⟨Piercing⟩ no tiene más ⟨Piercing⟩ cuando llega la fase de check, igualmente va a realizar los checks porque solo necesitaba tener la keyword al momento de ganar la batalla',
      'Si el oponente no tiene seguridades cuando un Digimon activa ⟨Piercing⟩, no pasa nada, y no termina la partida',
      '⟨Piercing⟩ tiene el mismo timing que todos los efectos [On Deletion] y “when a Digimon is deleted”, así que el jugador de turno puede activar  ⟨Piercing⟩ en cualquier orden, y el jugador defensor debe esperar a que  ⟨Piercing⟩ haya activado para activar sus [On Deletion]. Quitarle  ⟨Piercing⟩ al Digimon oponente con un [On Deletion] no va a evitar que se realicen los checks.',
      '⟨Piercing⟩ no activa en el turno del oponente',
      'Si el Digimon atacado pierde la batalla pero utiliza un efecto para evitar ser borrado, ⟨Piercing⟩ no activa',
      'Si el Digimon con ⟨Piercing⟩ borra a un Digimon oponente que bloqueó, ⟨Piercing⟩ activa normalmente',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 5,
  },
  {
    name: 'Draw X',
    slug: 'draw-x',
    reminderText: 'Robá X cartas.',
    category: 'Activa Obligatoria',
    interruptive: 'No',
    area: 'N/A',
    debut: 'BT1',
    colors: 'Todos',
    summary:
      'Keyword de robo simple que agrega cartas del mazo a tu mano.',
    tips: [
      'Si el jugador no tiene cartas en su mazo, el efecto no hace nada, y el jugador no pierde la partida',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 6,
  },
  {
    name: 'Jamming',
    slug: 'jamming',
    reminderText: 'Este Digimon no es eliminado en batallas contra Digimon de security.',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT2',
    colors: 'Todos / Azul',
    summary:
      'Protege a este Digimon de ser eliminado por batallas contra Digimon que salgan de security.',
    tips: [
      'Los efectos de seguridad de las cartas chequeadas activan normalmente y son capaces de afectar al Digimon que está atacando con ⟨Jamming⟩ ',
      'Si un Digimon pasa a tener ⟨Jamming⟩ en el medio de estar chequeando seguridades, el resto de las seguridades que tenga que chequear serán con ⟨Jamming⟩ ',
      'Si un Digimon deja de tener ⟨Jamming⟩ por algún efecto a causa de una seguridad siendo revelada, va a pelear contra esa seguridad (y las siguientes) sin ⟨Jamming⟩, ya que la batalla es lo último en ocurrir',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 7,
  },
  {
    name: 'Digisorption -X',
    slug: 'digisorption-minus-x',
    reminderText: 'Al digievolucionar desde la mano, podés suspender uno de tus Digimon para reducir el coste en X.',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'BT2',
    colors: 'Verde',
    summary:
      'Permite reducir el coste de digievolución usando la suspensión de uno de tus Digimon como recurso.',
    tips: [
      'El Digimon que se suspende por este efecto debe suspenderse luego de mostrar la carta con ⟨Digisorption⟩ pero antes de realizar la digievolución.',
      'El mismo Digimon que va a digievolucionar en esta carta puede usarse para suspenderse y reducir el coste. Si ese Digimon tenía un efecto “when this Digimon suspends”, no va a poder activarlo, ya que lo pierde cuando evoluciona. ',
      'Al ser un efecto interruptivo y no estar produciendo la digievolución, es posible combinarlo con otros efectos interruptivos, y con un efecto que haya producido la digievolución',
      'Si ninguno de nuestros Digimon puede digievolucionar en la carta que tiene ⟨Digisorption⟩, no es posible activar el efecto para suspender algo',
      '⟨Digisorption⟩ dispara todos los efectos “when a Digimon suspends by effect”, pero no “when a Digimon digivolves by effect”, ya que ⟨Digisorption⟩ no produce una digievolución, la interrumpe.',
      'Si ⟨Digisorption⟩ fuera a reducir el costo a menos de 0, simplemente se queda en 0',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 8,
  },
  {
    name: 'Reboot',
    slug: 'reboot',
    reminderText: 'Este Digimon también se desuspende en la fase de desuspensión del oponente.',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT2',
    colors: 'Negro',
    summary:
      'Hace que este Digimon vuelva a desuspenderse en el turno rival, ayudando a combinar ataque y defensa.',
    tips: [
      'Es obligatorio desuspender a un Digimon con ⟨Reboot⟩ en la Unsuspend Phase del oponente',
      'Los Digimon del jugador de turno y los Digimon oponentes con ⟨Reboot⟩ se desuspenden todos al mismo tiempo',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 9,
  },
  {
    name: 'De-Digivolve X',
    slug: 'de-digivolve-x',
    reminderText: 'Retirá hasta X cartas de la parte superior de las fuentes del objetivo sin pasar de nivel 3.',
    category: 'Activa Obligatoria',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT2',
    colors: 'Negro',
    summary:
      'Reduce una pila de digievolución quitando cartas desde arriba sin bajar de nivel 3.',
    tips: [
      '⟨De-Digivolve⟩ no hace que el Digimon afectado deje el Battle Area, y no activa protecciones que evitan esto',
      'Como ⟨De-Digivolve X⟩ es un “up to X”, el jugador que hace el efecto elige de antemano cuántas cartas descartar, entre 1 y X',
      'Si el efecto no aclara que tiene que ser al oponente, es posible hacerle ⟨De-Digivolve⟩ a un Digimon propio.',
      'No es posible hacer ⟨De-Digivolve 0⟩, pero sí es posible elegir un Digimon que no sea posible hacerle ⟨De-Digivolve⟩ para no hacer nada',
      'Incluso si un Digimon nivel 3 tiene digivolution cards, no es posible hacerle ⟨De-Digivolve⟩. ',
      'Todas las cartas de ⟨De-Digivolve⟩ se descartan al mismo tiempo',
      'Si en el medio de un ⟨De-Digivolve⟩ hay una carta que haría a la pila inmune, igualmente se puede descartar esa carta porque se descartan todas a la vez.',
      'Si luego de ⟨De-Digivolve⟩ el Digimon queda como un Tamer, se lo deja de considerar un Digimon al terminar el efecto y queda como Tamer. ',
      'Si el Digimon que ahora es un Tamer estaba atacando, el ataque termina sin batalla. ',
      'Si el Digimon que ahora es un Tamer vuelve a digievolucionar a un Digimon, va a seguir teniendo todos los efectos temporarios aplicados que tenía antes de que le hagan ⟨De-Digivolve⟩',
      'Si luego de ⟨De-Digivolve⟩ el Digimon queda como una carta nivel 2 sin DP impreso o una Option, se descarta. Esto no cuenta como delete. ',
      'Si estamos haciendo ⟨De-Digivolve X⟩ con un X mayor a 1, es posible pasar por Tamers, Options y Digi-Egg y seguir descartando, ya que hasta que el efecto no se termina, el juego no se fija qué quedó como tope de la pila. La pila se va a considerar un Digimon hasta que el efecto termine.',
      'Si un efecto pide que hagamos ⟨De-Digivolve 1⟩ por cada X, no debemos hacer ⟨De-Digivolve X⟩, sino ⟨De-Digivolve 1⟩ X veces. En este caso, no se puede elegir un valor menor a X (ya que ⟨De-Digivolve 1⟩ siempre es mínimo 1) y el juego se fija en cada descarte que la carta del tope no sea inmune a efectos. Si se llega a una carta inmune, los próximos ⟨De-Digivolve 1⟩ no van a poderse procesar y se frena ahí. ',
      'Si el efecto de un Digimon dispara (triggerea) pero sufre ⟨De-Digivolve⟩ antes de poder activarlo, causando así que lo deje de tener, no va a poder activar ese efecto',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 10,
  },
  {
    name: 'Retaliation',
    slug: 'retaliation',
    reminderText: 'Si este Digimon es eliminado por perder una batalla, también elimina al Digimon contra el que peleó.',
    category: 'Activa Obligatoria',
    interruptive: 'No',
    area: 'Trash',
    debut: 'BT2',
    colors: 'Violeta',
    summary:
      'Convierte una derrota en batalla en un intercambio, eliminando también al Digimon rival involucrado.',
    tips: [
      '⟨Retaliation⟩ activa en el trash, junto con todos los efectos [On Deletion] que pueda tener el Digimon. Si el Digimon deja de estar en el trash antes de activar ⟨Retaliation⟩, no va a poder activarlo',
      '⟨Retaliation⟩ cuenta como destrucción por efecto',
      '⟨Retaliation⟩ debe respetar la prioridad de turno. Es decir, si el Digimon atacante era el que tenía ⟨Retaliation⟩, va activar antes de los efectos “when a Digimon is deleted” del oponente, y si el Digimon defensor es el que tenía ⟨Retaliation⟩, va a activar después de los efectos “when a Digimon is deleted” del oponente',
      'Si un Digimon tiene ⟨Retaliation⟩ varias veces, tiene que activarlas una por una. Es decir, si el Digimon oponente sobrevive una instancia de ⟨Retaliation⟩, se aplica la siguiente para intentar destruirlo de nuevo.',
      'Si un Digimon con ⟨Piercing⟩ ataca y destruye a otro con ⟨Retaliation⟩, ⟨Piercing⟩ va a activar, pero si el Digimon atacante es destruído por ⟨Retaliation⟩, no va a poder realizar checks',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 11,
  },
  {
    name: 'Digi-Burst X',
    slug: 'digi-burst-x',
    reminderText: 'Descartá X fuentes de este Digimon para habilitar el efecto indicado.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT4',
    colors: 'Todos',
    summary:
      'Usa cartas de digievolución como recurso para activar efectos adicionales.',
    tips: [
      'Es necesario descartar la cantidad especificada por X para activar el efecto. Si no nos alcanzan las sources que podemos descartar, no podemos activar el efecto ni descartar nada.',
      'Los efectos de las sources que fueron descartadas van a activar una vez terminado el efecto de ⟨Digi-Burst⟩, con el mismo timing que cualquier otro efecto que haya disparado a raíz del ⟨Digi-Burst⟩ ',
      'Solo se pueden descartar sources del Digimon que está queriendo activar ⟨Digi-Burst⟩, no de otros Digimon, y todas se descartan al mismo tiempo. ',
      'Si un efecto dice ⟨Digi-Burst up to X⟩ significa que el jugador puede descartar una cantidad de sources entre 1 y X para activar el efecto ',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 12,
  },
  {
    name: 'Rush',
    slug: 'rush',
    reminderText: 'Este Digimon puede atacar el turno en que fue jugado.',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT4',
    colors: 'Todos',
    summary:
      'Permite atacar inmediatamente después de ser jugado, sin esperar un turno.',
    tips: [
      'Si un Digimon gana ⟨Rush⟩ luego de ser jugado, ya sea por una digievolución a un Digimon con ⟨Rush⟩ o un efecto que le dé ⟨Rush⟩ por el turno, va a poder atacar ese turno ',
      'Si un Digimon deja de tener ⟨Rush⟩ luego de ser jugado, por ejemplo, por una digievolución a un Digimon sin ⟨Rush⟩, ya no va a poder atacar el turno que fue jugado',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 13,
  },
  {
    name: 'Blitz',
    slug: 'blitz',
    reminderText: 'Este Digimon puede atacar aunque la memoria haya quedado del lado del rival.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT5',
    colors: 'Rojo / Negro',
    summary:
      'Permite declarar un ataque incluso si la memoria ya pasó al lado del oponente.',
    tips: [
      '⟨Blitz⟩ siempre está acompañada de un trigger ([When Digivolving] u [On Play]) y no es un efecto pasivo que simplemente activa cuando pasamos la memoria al lado del oponente. Si al triggerear ⟨Blitz⟩, la memoria sigue de nuestro lado, ⟨Blitz⟩ no va a activar y ya se perdió.',
      'Para atacar con ⟨Blitz⟩ el Digimon debe poder atacar normalmente fuera de ⟨Blitz⟩. Es decir, estar en el turno propio, no estar suspendido, no estar afectado por “can’t attack”, no haberse jugado ese turno (sin tener ⟨Rush⟩), etc. ⟨Blitz⟩ no ignora ninguna regla del proceso de ataque.',
      '⟨Blitz⟩ no activa en [End of Turn]. Una vez que termina el ataque por ⟨Blitz⟩, recién ahí triggerea [End of Turn], asumiendo que no ganamos memoria por haber atacado. Es posible atacar nuevamente con un efecto [End of Turn] luego de haber atacado con ⟨Blitz⟩ si se dan las condiciones.',
      'Si un Digimon ataca con ⟨Blitz⟩, sus [When Attacking] van a pasar a tener prioridad sobre el resto de los efectos [When Digivolving] (u [On Play]), y va a tener que activarlos inmediatamente, incluyendo los efectos “when a Digimon attacks” del oponente',
      'Si un Digimon ataca con ⟨Blitz⟩, el ataque no va a avanzar a Counter Timing hasta no terminar el resto de sus efectos [When Digivolving] (u [On Play])',
      'Si un Digimon ataca con ⟨Blitz⟩, pero tiene ⟨Blitz⟩ dos veces, no hay manera de que lo active dos veces, porque los efectos [When Digivolving] u [On Play] deben terminar de activarse en su totalidad antes de avanzar el ataque, y no pueden declararse dos ataques a la vez.',
      '⟨Blitz⟩ no cuenta como suspenderse por efecto; la keyword te hizo atacar, y atacar es lo que te hizo suspenderte',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 14,
  },
  {
    name: 'Delay',
    slug: 'delay',
    reminderText: 'Esta carta puede descartarse desde la battle area para usar el efecto inferior; no puede hacerlo el turno en que entró.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'ST7 / ST8',
    colors: 'Todos',
    summary:
      'Keyword propia de algunas Options que permanecen en mesa y guardan un efecto para usar más adelante.',
    tips: [
      'Las Option en la Battle Area no otorgan color para cumplir los requisitos de color de otras Option',
      'Activar ⟨Delay⟩ no cuenta como usar una Option, y no se necesita tener algo del color para activar ⟨Delay⟩',
      'Incluso si el ⟨Delay⟩ de una option es en respuesta a un trigger, siempre es opcional',
      'Si una Option se setea en la battle area como parte de un efecto de seguridad, se va a poder activar su ⟨Delay⟩ una vez que empiece el turno de su dueño',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 15,
  },
  {
    name: 'Decoy X',
    slug: 'decoy-x',
    reminderText: 'Si otro de tus Digimon X fuera a ser eliminado por un efecto rival, este puede eliminarse en su lugar para evitarlo.',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'BT6',
    colors: 'Negro / Rojo',
    summary:
      'Protección por reemplazo que sacrifica este Digimon para salvar a otro aliado válido.',
    tips: [
      '⟨Decoy X⟩ solo puede activarse cuando un Digimon que cumpla con la condición de ser X vaya a ser destruído por efecto del oponente. No sirve para prevenir destrucción por batalla, por DP, por efectos propios o irse de la Battle Area por cualquier otra razón.',
      'Si activamos ⟨Decoy⟩ pero el Digimon con ⟨Decoy⟩ no logra ser destruído (por ejemplo, tiene una protección), el Digimon que estamos intentando salvar va a ser destruído, porque destruir al Digimon con ⟨Decoy⟩ es el costo del efecto',
      '⟨Decoy⟩ cuenta como destrucción por efecto propio. Si un efecto del oponente intenta destruir un Digimon y luego se fija si fue destruído por ese efecto, los Digimon que fueron destruídos por ⟨Decoy⟩ no van a considerarse destruídos por ese efecto (sino por el mismo ⟨Decoy⟩)',
      'Cada Digimon con ⟨Decoy⟩ puede salvar a un Digimon que va a ser destruído en el caso que varios fueran a ser destruídos a la vez. Por ejemplo, si tengo dos Digimon con ⟨Decoy⟩ y me van a destruir cuatro al mismo tiempo, puedo destruir a los dos con ⟨Decoy⟩ para salvar a los otros dos. ',
      'Si un Digimon va a ser destruído por efecto del oponente y tengo dos o más Digimon con ⟨Decoy⟩, puedo destruir a ambos por efecto de ⟨Decoy⟩, incluso si ya el segundo no está evitando ninguna destrucción, ya que los efectos no se “destriggerean”',
      'Si un Digimon inmune a destrucción o efectos intenta ser destruido por un efecto del oponente, no se puede activar ⟨Decoy⟩ porque no va a estar intentando ser destruido realmente',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 16,
  },
  {
    name: 'Armor Purge',
    slug: 'armor-purge',
    reminderText: 'Si este Digimon fuera a ser eliminado, puede descartar su fuente superior para evitarlo.',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'BT8',
    colors: 'Todos',
    summary:
      'Protección clásica de los Armor Digimon, evitando la eliminación a cambio de perder la fuente superior.',
    tips: [
      '⟨Armor Purge⟩ no puede activarse si el Digimon no tiene sources, porque los Digimon sin sources no tienen “top card”',
      '⟨Armor Purge⟩ puede activarse con cualquier tipo de destrucción, ya sea batalla, efecto o 0 DP',
      'Si ⟨Armor Purge⟩ se activa para salvarse de perder una batalla, el ⟨Piercing⟩ del Digimon que atacó no va a activar',
      'Si ⟨Armor Purge⟩ se activa para salvarse de perder una batalla teniendo ⟨Retaliation⟩, el Digimon del oponente no va a ser destruído ',
      'Si ⟨Armor Purge⟩ se activa para salvarse de ser destruído por efecto, el efecto va a considerar que no destruyó nada',
      'Si ⟨Armor Purge⟩ se activa para salvarse de ser destruido por 0 DP, y el Digimon sigue teniendo 0 DP después de ⟨Armor Purge⟩, va a intentar ser destruido de nuevo ',
      'Si ⟨Armor Purge⟩ se activa durante chequeos de seguridad, pero el Digimon sigue teniendo checks pendientes, los va a realizar luego de ⟨Armor Purge⟩',
      'Si ⟨Armor Purge⟩ hace que la pila quede en un Digi-Egg sin DP o una Option, se descarta la pila (no cuenta como destrucción)',
      'Si ⟨Armor Purge⟩ hace que la pila quede en un Tamer, simplemente queda el Tamer en la Battle Area y deja de ser un Digimon cuando termine el efecto o batalla que lo intentó destruir ',
      'Si se activa ⟨Armor Purge⟩ para salvar al Digimon, igualmente van a seguirse activando otros efectos “when this Digimon would be deleted” o “when this Digimon would leave the Battle Area”, como por ejemplo X-Antibody Proto Form.',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 17,
  },
  {
    name: 'Save',
    slug: 'save',
    reminderText: 'Esta carta puede colocarse debajo de uno de tus Tamers.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Trash',
    debut: 'BT10',
    colors: 'Todos',
    summary:
      'Permite guardar esta carta debajo de un Tamer para aprovecharla más adelante.',
    tips: [
      '⟨Save⟩ siempre es un efecto [On Deletion] y activa desde el trash junto con el resto de los efectos de ese tipo',
      '⟨Save⟩ siempre coloca las cartas debajo de todas las sources ya existentes de un Tamer ',
      'Los Tamer con cartas con hereditarias debajo no las pueden activar, ya que solo los Digimon pueden tener “digivolution cards”, los Tamer solo tienen “cards under”. ',
      '⟨Save⟩ hace que el Digimon ya no pueda activar [On Deletion]s pendientes, así que hay que tener cuidado en el órden que se resuelven los efectos',
      'Las cartas que tienen solamente ⟨Material Save⟩ no tienen ⟨Save⟩ en el texto ',
      'Si un oponente le dió un efecto [On Deletion] a uno de mis Digimon, puedo declarar ⟨Save⟩ antes que ese efecto para no tener que activarlo ',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 18,
  },
  {
    name: 'Material Save X',
    slug: 'material-save-x',
    reminderText: 'Si este Digimon fuera a ser eliminado, podés colocar X materiales válidos de sus fuentes debajo de uno de tus Tamers.',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'BT10',
    colors: 'Todos',
    summary:
      'Rescata materiales desde las fuentes de este Digimon y los guarda debajo de un Tamer.',
    tips: [
      'Solo es posible guardar materiales que aparezcan en los requisitos de DigiXros del Digimon',
      'Es posible guardar varias copias del mismo Digimon, incluso si solo aparece una vez en los requisitos de DigiXros',
      'Si se tienen menos de X materiales válidos al momento de elegir activar ⟨Material Save X⟩, se guardan todos',
      'Si se activa ⟨Material Save X⟩, deben guardarse X, o lo máximo posible si hay menos de X. No se puede elegir guardar menos de lo posible ',
      'Al ser interruptivo, ⟨Material Save⟩ actiiva con el Digimon todavía en la Battle Area',
      'Las cartas que tienen solamente ⟨Material Save⟩ no tienen ⟨Save⟩ en el texto ',
      'Es posible guardar cartas que no fueron agregadas específicamente por DigiXros ',
      'Si una carta tiene el rule “this card/Digimon is also treated as X”, puede guardarse usando el ⟨Material Save⟩ de un Digimon que hace DigiXros con X',
      'Si una carta tiene el efecto “this card is treated as X for a DigiXros”, no puede guardarse usando el ⟨Material Save⟩ de un Digimon que hace DigiXros con X, ya que una vez que ya está abajo, no tiene más ese nombre',
      'Los efectos [On Deletion] y los efectos disparados por agregarles cartas a los Tamer se consideran triggereados al mismo tiempo ',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 19,
  },
  {
    name: 'Evade',
    slug: 'evade',
    reminderText: 'Si este Digimon fuera a ser eliminado, podés suspenderlo para evitarlo.',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'BT11',
    colors: 'Azul',
    summary:
      'Permite evitar la eliminación suspendiendo a este Digimon.',
    tips: [
      'Si el Digimon no puede suspenderse a raíz un efecto, o ya está suspendido, no puede activar ⟨Evade⟩ ',
      'Si ⟨Evade⟩ se activa para salvarse de perder una batalla, el ⟨Piercing⟩ del Digimon que atacó no va a activar',
      'Si ⟨Evade⟩ se activa para salvarse de perder una batalla teniendo ⟨Retaliation⟩, el Digimon del oponente no va a ser destruído ',
      'Si ⟨Evade⟩ se activa para salvarse de ser destruído por efecto, el efecto va a considerar que no destruyó nada',
      'Si ⟨Evade⟩ se activa para salvarse de ser destruido por 0 DP, y el Digimon sigue teniendo 0 DP, va a intentar ser destruido de nuevo antes de activar los efectos “when a Digimon suspends”',
      'Aunque ⟨Evade⟩ sea interruptivo, un efecto que diga “when this Digimon suspends, it unsuspends” no lo es, así que un efecto que primero suspenda y luego destruya o destruya dos veces va a terminar de resolverse antes de que el Digimon se desuspenda y pueda usar ⟨Evade⟩ por segunda vez',
      '⟨Evade⟩ cuenta como suspenderse por efecto',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 20,
  },
  {
    name: 'Raid',
    slug: 'raid',
    reminderText: 'Al atacar, puede cambiar el objetivo a un Digimon rival desuspendido con el mayor DP.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT11',
    colors: 'Rojo',
    summary:
      'Permite redirigir el ataque a un Digimon rival desuspendido de alto DP para forzar una batalla.',
    tips: [
      'Si el oponente tiene varios Digimon desuspendidos que comparten el mayor DP, el jugador que activa ⟨Raid⟩ puede elegir a cuál redirigir ',
      'El DP más alto solo se elige entre los Digimon desuspendidos, los suspendidos se ignoran completamente',
      'El DP más alto se determina al momento de activar ⟨Raid⟩, no al momento de atacar',
      'Al tener el trigger “when this Digimon attacks”, ⟨Raid⟩ se va a activar en cualquier orden con el resto de los efectos [When Attacking] del jugador de turno, pero no es inhabilitado por efectos que no dejen activar efectos [When Attacking]',
      'Al tener el trigger “when this Digimon attacks”, el Digimon debe tener ⟨Raid⟩ en el momento que declara el ataque. Si lo gana más adelante, por ejemplo, por digievolucionar a un Digimon con ⟨Raid⟩ atacando, no va a poder activar ',
      '⟨Raid⟩ no afecta a qué objetivo se atacó, solo cambia el objetivo del ataque. Es decir, es posible activar ⟨Raid⟩ hacia un Digimon que tiene el efecto “this Digimon can’t be attacked”',
      '⟨Raid⟩ puede activarse ya sea si se atacó a un Digimon o al jugador. El objetivo original del ataque es el que determinará qué efectos disparan, los “when this Digimon attacks a player” o “when this Digimon attacks a Digimon” ',
      'Si el Digimon que tiene ⟨Raid⟩ no tiene ningún objetivo válido de ataque inicialmente, no va a poder atacar y por ende no va a poder activar ⟨Raid⟩ ',
      '⟨Raid⟩ dispara los efectos “when attack targets change” ',
      'Al ser un efecto del jugador de turno, el objetivo de ataque puede volver a cambiar si el oponente activa un efecto que redirige el ataque a otro Digimon, o bloquea.',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 21,
  },
  {
    name: 'Alliance',
    slug: 'alliance',
    reminderText: 'Al atacar, podés suspender otro Digimon propio; este gana su DP y Security A. +1 durante ese ataque.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'EX4',
    colors: 'Inicialmente Verde, hoy transversal',
    summary:
      'Convierte otro Digimon de tu mesa en apoyo ofensivo para aumentar el DP y la presión de security.',
    tips: [
      'El DP y el check son ganados sólo durante ese ataque. Al terminar el ataque, se pierden los bonus',
      'El DP ganado se calcula en el momento que se termina de suspender el otro Digimon, ya habiendo aplicado los efectos pasivos que cambian DP si algo está suspendido',
      'Si el Digimon suspendido por ⟨Alliance⟩ pasa a tener 0 DP, primero el Digimon atacante gana 0 DP y ⟨Security A. +1⟩, luego el Digimon con 0 DP es destruído inmediatamente',
      'No se puede usar ⟨Alliance⟩ para suspender a un Digimon con el efecto “this Digimon can’t suspend”',
      'Lo que le pase al Digimon suspendido para hacer ⟨Alliance⟩ es irrelevante, solo necesita existir al momento de suspenderse. La única manera de perder los bonus de ⟨Alliance⟩ es terminando el ataque',
      'Si un Digimon pierde DP durante su ataque, cosa que su DP sin ⟨Alliance⟩ sería 0, va a ser destruído al finalizar el ataque',
      'El ataque se considera terminado cuando se terminaron de resolver todos los efectos iniciales, batalla y efectos derivados de la batalla, y se vuelve a un estado de juego donde el jugador puede tomar una acción nueva. Recién en ese momento se acaba ⟨Alliance⟩. ',
      'Al tener el trigger “when this Digimon attacks”, el Digimon debe tener ⟨Alliance⟩ en el momento que declara el ataque. Si lo gana más adelante, por ejemplo, por digievolucionar a un Digimon con ⟨Alliance⟩ atacando, no va a poder activar ',
      '⟨Alliance⟩ cuenta como suspenderse por efecto',
      'Es posible tener varias instancias de  ⟨Alliance⟩, lo que permite al Digimon suspender un Digimon por cada instancia de ⟨Alliance⟩ que tenga y ganar un check y DP por cada uno.',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 22,
  },
  {
    name: 'Barrier',
    slug: 'barrier',
    reminderText: 'Si este Digimon fuera a ser eliminado en batalla, podés mandar al trash la security superior para evitarlo.',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'BT13',
    colors: 'Amarillo',
    summary:
      'Protección contra eliminación en batalla que usa tu security como costo.',
    tips: [
      'Destrucción por batalla cuenta tanto para Digimon contra Digimon y contra Digimon de seguridad',
      'Solo es posible descartar la carta del tope de la seguridad para activar ⟨Barrier⟩ ',
      'Si se tienen varias instancias de ⟨Barrier⟩ en la misma pila, es posible descartar una seguridad por cada una, aunque el Digimon ya haya sido salvado por la primera ',
      'Cartas descartadas por ⟨Barrier⟩ van a activar sus efectos “when this card is trashed from your security stack” y los efectos “when security stacks are removed from” ',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 23,
  },
  {
    name: 'Blast Digivolve',
    slug: 'blast-digivolve',
    reminderText: 'En Counter Timing, uno de tus Digimon puede digievolucionar a esta carta desde la mano sin pagar memoria.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Mano',
    debut: 'ST15 / ST16',
    colors: 'Todos',
    summary:
      'Permite digievolucionar desde la mano durante el turno rival en el Counter Timing sin pagar memoria.',
    tips: [
      '⟨Blast Digivolve⟩ cuenta como digievolucionar por efecto',
      '⟨Blast Digivolve⟩ siempre respeta los requisitos de digievolución normales de la carta (es decir, los de color+nivel y las cajas negras) pero siempre cuesta 0 de memoria ',
      'No es posible hacer ⟨Blast Digivolve⟩ sobre un Tamer',
      'No es posible hacer ⟨Blast Digivolve⟩ sobre un Digimon que está afectado por “this Digimon can’t digivolve” ',
      'El jugador que hace ⟨Blast Digivolve⟩ debe robar una carta por el bonus de digievolución',
      'Solamente se permite activar un efecto [Counter] por ataque (es decir, si se usó ⟨Blast Digivolve⟩ una vez, no se puede hacer de nuevo ni activar ⟨Blast DNA Digivolve⟩ en el mismo ataque)',
      'Si el jugador de turno tiene algún efecto que reaccione a un Digimon del oponente digievolucionando, éste se activará antes que el [When Digivolving] del ACE',
      'Los efectos derivados de la evolución por ⟨Blast Digivolve⟩ deben activarse por completo antes de poder avanzar a Block Timing',
      'Si el Digimon atacante no existe más para cuando llega Counter Timing, igualmente es posible activar ⟨Blast Digivolve⟩ ',
      'Si un efecto finaliza el ataque durante la fase de [When Attacking], se saltea el Counter Timing y no hay ventana para activar ⟨Blast Digivolve⟩ ',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 24,
  },
  {
    name: 'Mind Link',
    slug: 'mind-link',
    reminderText: 'Este Tamer puede colocarse bajo un Digimon válido que no tenga ya otro Tamer entre sus fuentes.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT14',
    colors: 'Todos (Digimon Seekers)',
    summary:
      'Permite que ciertos Tamers pasen a ser material debajo de un Digimon para generar nuevas sinergias.',
    tips: [
      'Aunque no sea posible activar ⟨Mind Link⟩ para poner el Tamer debajo de un Digimon que ya tenga un Tamer, nada evita que se ponga un Tamer que tenga ⟨Mind Link⟩ debajo de un Digimon que ya tenga un Tamer por otros medios',
      'Al igual que cualquier otra mecánica que cause que una pila salga de la Battle Area, ⟨Mind Link⟩ descarta las sources del Tamer antes de que se ponga debajo del Digimon',
      'El efecto ⟨End of All Turns⟩ que tienen los Tamer con  ⟨Mind Link⟩ cuenta como jugar un Tamer por efecto',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 25,
  },
  {
    name: 'Fortitude',
    slug: 'fortitude',
    reminderText: 'Si este Digimon es eliminado mientras tiene fuentes, se juega nuevamente sin pagar coste.',
    category: 'Activa Obligatoria',
    interruptive: 'No',
    area: 'Trash',
    debut: 'EX5',
    colors: 'Verde',
    summary:
      'Hace que este Digimon vuelva al campo después de ser eliminado si tenía fuentes.',
    tips: [
      'Jugarse por ⟨Fortitude⟩ cuenta como jugar un Digimon por efecto',
      'El Digimon jugado por ⟨Fortitude⟩ se considera un Digimon nuevo que no tiene ninguno de los efectos aplicados que tenía antes de ser destruido ',
      'Incluso si las sources del Digimon salen del trash antes de activar ⟨Fortitude⟩, mientras el Digimon haya tenido sources al momento de ser destruido, y siga estando en el trash, se va a jugar',
      'Luego de activar ⟨Fortitude⟩, y posteriormente a los efectos ⟨On Play⟩ del Digimon, ya no van a poder activarse el resto de los efectos [On Deletion] pendientes del Digimon, ya que no está más en el trash',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 26,
  },
  {
    name: 'Partition',
    slug: 'partition',
    reminderText: 'Si este Digimon fuera a dejar la battle area por una causa válida, podés jugar las piezas especificadas desde sus fuentes sin pagar coste.',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'BT16',
    colors: 'Todos',
    summary:
      'Cuando esta pila sale del campo, puede desarmarse y volver a poner en juego piezas específicas desde sus fuentes.',
    tips: [
      'Jugarse por ⟨Partition⟩ cuenta como jugar un Digimon por efecto y como jugar un Digimon de digivolution cards',
      'Si el Digimon no tiene ambas cartas debajo que cada una cumpla al menos una de las condiciones, ⟨Partition⟩ no dispara',
      'Si el Digimon tiene varias cartas que cumplan alguna de las condiciones de ⟨Partition⟩, debe elegir uno para jugar para cada una',
      'Si ⟨Partition⟩ se activa, es obligatorio intentar jugar ambos Digimon. Si uno de los Digimon no puede ser jugado por algún efecto que lo prohíba, pero el otro sí, se juega el que se puede jugar ',
      '⟨Partition⟩ activa por 0 DP, ya que no es ni un efecto ni batalla',
      'Si un Digimon con ⟨Partition⟩ tanto arriba como también en su heredada fuera a dejar la Battle Area pero hay otro efecto interruptivo que lo va a hacer digievolucionar, debe activarse ⟨Partition⟩ primero. Si se decide digievolucionar al Digimon antes de activar ⟨Partition⟩, el ⟨Partition⟩ heredado no va a haber triggereado y no se puede activar. ',
      'Si un Digimon tiene ⟨Partition⟩ varias veces, va a poder activarlo las veces que quiera siempre y cuando siga teniendo el par de Digimon que pide la keyword para cada uso.',
      'Los efectos que le cambian el color a un Digimon son irrelevantes para ⟨Partition⟩ ya que estos efectos no cambian el color de las sources',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 27,
  },
  {
    name: 'Collision',
    slug: 'collision',
    reminderText: 'Mientras este Digimon ataca, todos los Digimon rivales ganan Blocker y el oponente debe bloquear si puede.',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT16',
    colors: 'Negro',
    summary:
      'Fuerza el combate obligando al oponente a bloquear si tiene una forma válida de hacerlo.',
    tips: [
      'Si un Digimon tiene ⟨Collision⟩ durante alguna parte de su ataque pero lo pierde para cuando llega Counter Timing, el efecto no va a ocurrir y el oponente no va a tener que bloquear',
      'Si un Digimon gana ⟨Collision⟩ durante alguna parte de su ataque y lo tiene cuando llega Counter Timing, el efecto va a ocurrir y el oponente va a tener que bloquear',
      'Un Digimon inmune a efectos no va a ganar ⟨Blocker⟩ a causa de ⟨Collision⟩, pero como ⟨Collision⟩ obliga al jugador a bloquear, el oponente va a tener que bloquear si su único Digimon es inmune pero también tiene ⟨Blocker⟩ por sí mismo',
      'Si el oponente tiene solo Digimon inmunes sin ⟨Blocker⟩, ⟨Collision⟩ no va a obligar al oponente a bloquear ya que no tiene con qué ',
      'Los Digimon del oponente van a ser ⟨Blocker⟩ todo el tiempo que un Digimon esté atacando y tenga ⟨Collision⟩. Es decir, los efectos que hacen cosas con Blockers van a poder elegir como objetivo a los Digimon del oponente durante un ataque con ⟨Collision⟩, incluso fuera del Block Timing.',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 28,
  },
  {
    name: 'Scapegoat',
    slug: 'scapegoat',
    reminderText: 'Si este Digimon fuera a ser eliminado por algo que no sea uno de tus propios efectos, podés eliminar otro de tus Digimon para salvarlo.',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'EX6',
    colors: 'Violeta',
    summary:
      'Permite sacrificar otro Digimon propio para evitar que este sea eliminado.',
    tips: [
      '⟨Scapegoat⟩ puede activarse para 0 DP, pero el Digimon va a seguir intentando ser destruido por tener 0 DP. Es posible activarlo varias veces para destruirse todos los Digimon que quieras hasta que no haya más o no quieras seguir activando ⟨Scapegoat⟩ ',
      'Si activamos ⟨Scapegoat⟩ pero el otro Digimon que estamos queriendo destruir no logra ser destruído (por ejemplo, tiene una protección), el Digimon que estamos intentando salvar va a ser destruído, porque destruir a otro Digimon es el costo del efecto',
      '⟨Scapegoat⟩ cuenta como destrucción por efecto propio. Si un efecto del oponente intenta destruir un Digimon y luego se fija si fue destruído por ese efecto, los Digimon que fueron destruídos por ⟨Scapegoat⟩  no van a considerarse destruídos por ese efecto',
      'Si un Digimon va a ser destruido varias veces por el mismo efecto, puede activar ⟨Scapegoat⟩ una vez por cada instancia de destrucción, destruyendo a otro de sus Digimon por cada una ',
      'Si varios Digimon con ⟨Scapegoat⟩ van a ser destruidos al mismo tiempo, cada uno puede destruir un Digimon diferente para salvarse',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 29,
  },
  {
    name: 'Blast DNA Digivolve',
    slug: 'blast-dna-digivolve',
    reminderText: 'En Counter Timing, una pieza desde el campo y otra desde la mano pueden hacer DNA hacia esta carta sin pagar coste.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Mano',
    debut: 'EX6',
    colors: 'Todos',
    summary:
      'Versión reactiva de DNA Digivolution que puede activarse en el turno rival sin pagar memoria.',
    tips: [
      '⟨Blast DNA Digivolve⟩ cuenta como digievolucionar por efecto',
      '⟨Blast DNA Digivolve⟩, aparte de los nombres que especifica, sigue respetando los requisitos de DNA normales. Es decir, deben cumplirse al mismo tiempo los requisitos de nombre, de color y de nivel.',
      'No es posible hacer ⟨Blast DNA Digivolve⟩ sobre un Digimon que está afectado por “this Digimon can’t digivolve”',
      'El jugador que hace ⟨Blast DNA Digivolve⟩ debe robar una carta por el bonus de digievolución',
      'Solamente se permite activar un efecto [Counter] por ataque (es decir, si se usó ⟨Blast DNA Digivolve⟩ una vez, no se puede hacer de nuevo ni activar ⟨Blast Digivolve⟩ en el mismo ataque)',
      'Si el jugador de turno tiene algún efecto que reaccione a un Digimon del oponente digievolucionando, éste se activará antes que el [When Digivolving] del ACE',
      'Los efectos derivados de la evolución por ⟨Blast DNA Digivolve⟩ deben activarse por completo antes de poder avanzar a Block Timing',
      'Si el Digimon atacante no existe más para cuando llega Counter Timing, igualmente es posible activar ⟨Blast Digivolve⟩',
      'Si un efecto finaliza el ataque durante la fase de [When Attacking], se saltea el Counter Timing y no hay ventana para activar ⟨Blast DNA Digivolve⟩',
      'Si un efecto redirige el ataque a un Digimon, y ese Digimon se usa para digievolucionar con ⟨Blast DNA Digivolve⟩, el ataque ya no tendrá objetivo. Si no se bloquea, el ataque terminará sin batalla.',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 30,
  },
  {
    name: 'Vortex',
    slug: 'vortex',
    reminderText: 'Al final de tu turno, este Digimon puede atacar a un Digimon rival aunque haya sido jugado ese turno.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'EX7',
    colors: 'Verde / Wind Guardians',
    summary:
      'Permite realizar un ataque al final del turno, incluso si este Digimon fue jugado ese mismo turno.',
    tips: [
      '⟨Vortex⟩ no puede usarse para atacar a un jugador, pero pueden usarse efectos para que el ataque se redirija al jugador',
      'Si un Digimon ataca con ⟨Vortex⟩, no se van a poder activar más instancias de ⟨Vortex⟩ de otros Digimon, ya que todos los efectos [End of Turn] (tuyos y del oponente) deben activarse antes de Counter Timing. ',
      'Para atacar con ⟨Vortex⟩ el Digimon debe poder atacar normalmente fuera de ⟨Vortex⟩. Es decir, estar en el turno propio, no estar suspendido, no estar afectado por “can’t attack”, etc. ⟨Vortex⟩  solo ignora la regla de no atacar el turno que el Digimon es jugado. ',
      'Si un Digimon ataca con ⟨Vortex⟩, sus [When Attacking] van a pasar a tener prioridad sobre el resto de los efectos [End of Turn], y va a tener que activarlos inmediatamente, incluyendo los efectos “when a Digimon attacks” del oponente',
      '⟨Vortex⟩ no cuenta como suspenderse por efecto; la keyword te hizo atacar, y atacar es lo que te hizo suspenderte',
      'Como ⟨Vortex⟩ es un efecto [End of Turn], si se gana ⟨Vortex⟩ o se juega un Digimon con ⟨Vortex⟩ posteriormente al trigger [End of Turn], ese Digimon no va a poder activarlo ',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 31,
  },
  {
    name: 'Overclock (X)',
    slug: 'overclock-x',
    reminderText: 'Al final de tu turno, al eliminar un Token u otro Digimon válido, este Digimon puede atacar al jugador sin suspenderse.',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'EX7',
    colors: 'Amarillo',
    summary: 'Permite un ataque extra al final del turno destruyendo un Token u otro Digimon. Tiene el efecto de atacar sin suspenderse, tambien el digimon que esta suspendido puede atacar',
    tips: [
      '⟨Overclock⟩ no puede usarse para atacar a un Digimon, pero pueden usarse efectos para que el ataque se redirija a un Digimon',
      'Si un Digimon ataca con ⟨Overclock⟩, no se va a poder atacar con otras activaciones de ⟨Overclock⟩ de otros Digimon, ya que todos los efectos [End of Turn] (tuyos y del oponente) deben activarse antes de Counter Timing.',
      'Para atacar con ⟨Overclock⟩ el Digimon debe poder atacar normalmente fuera de ⟨Overclock⟩. Es decir, estar en el turno propio, no haber sido jugado ese turno, no estar afectado por “can’t attack”, etc. ⟨Overclock⟩ solo ignora la regla de tener que suspenderse para atacar.',
      'Incluso si el Digimon no puede atacar (ya sea porque ya se activó el ⟨Overclock⟩ de otro Digimon, o el Digimon no puede atacar ese turno), es posible activar ⟨Overclock⟩ solo para destruir otro de tus Digimon y no atacar',
      'Los efectos [When Attacking] del Digimon que atacó y los efectos [On Deletion] del Digimon que se destruyó se pueden activar en cualquier orden',
      'Si un Digimon ataca con ⟨Overclock⟩, sus [When Attacking] y los [On Deletion] del Digimon que se destruyó van a pasar a tener prioridad sobre el resto de los efectos [End of Turn], y va a tener que activarlos inmediatamente, incluyendo los efectos “when a Digimon attacks” del oponente',
      '⟨Overclock⟩ no cuenta como suspenderse por efecto; la keyword te hizo atacar, y atacar es lo que te hizo suspenderte. El Digimon que se destruye cuenta como destruido por efecto propio.',
      'Si el Digimon que se intenta destruir por ⟨Overclock⟩ no es destruido, no se puede atacar',
      'Como ⟨Overclock⟩ es un efecto [End of Turn], si se gana ⟨Overclock⟩ o se juega un Digimon con ⟨Overclock⟩ posteriormente al trigger [End of Turn], ese Digimon no va a poder activarlo',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 32,
  },
  {
    name: 'Iceclad',
    slug: 'iceclad',
    reminderText: 'Este digimon compara la cantidad de cartas de digievolucuion en lugar de DP en batalla, este efecto no aplica a la seguridad',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'EX7',
    colors: 'Azul',
    summary: '⟨Iceclad⟩ cambia las reglas de las batallas en las que participe uno o más Digimon con esta keyword. En vez de ganar el Digimon con más DP, gana el Digimon con más sources.',
    tips: [
      '⟨Iceclad⟩ no afecta a ningún Digimon, sino que solo cambia las reglas de la batalla, así que no se puede ser inmune a ⟨Iceclad⟩',
      'Si un Digimon pierde una batalla contra un Digimon con ⟨Iceclad⟩, se considera que fue destruido por batalla, no por efecto. por lo tanto, el Digimon que va a ser destruido puede activar protecciones que prevengan destrucción por batalla ',
      'Si ambos Digimon tienen la misma cantidad de sources, ambos Digimon van a ser destruidos en su batalla',
      '⟨Iceclad⟩ no afecta las batallas contra Digimon de seguridad',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 33,
  },
  {
    name: 'Decode (X)',
    slug: 'decode-x',
    reminderText: 'Cuando este Digimon fuera a dejar el área de batalla excepto por batalla, puedes jugar una carta de Digimon X de sus cartas de digievolución sin pagar el costo)',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'BT18',
    colors: 'Azul',
    summary:
      '⟨Decode (X)⟩ es un efecto interruptivo muy similar a ⟨Partition⟩, en el sentido que deja jugar sources cuando el Digimon va a dejar la Battle Area. En este caso, solo juega un Digimon en lugar de dos, pero, a cambio de eso, puede activarse con efectos propios. ⟨Decode⟩ siempre va a aclarar el nivel del Digimon que puede jugarse, y también puede agregar Trait y/o color al requerimiento. Por lo general lo tienen Digimon del arquetipo Aqua/Sea Animal ya que tienen muchos efectos para removerse entre ellos de la Battle Area.',
    tips: [
      'Jugarse por ⟨Decode⟩ cuenta como jugar un Digimon por efecto y como jugar un Digimon de digivolution cards',
      'Si el Digimon tiene varias cartas que cumplan la condición de ⟨Decode⟩, debe elegir uno para jugar',
      '⟨Decode⟩ activa por 0 DP, ya que no es batalla',
      'Los efectos que le cambian el color a un Digimon son irrelevantes para ⟨Decode⟩ ya que estos efectos no cambian el color de las sources',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 34,
  },
  {
    name: 'Fragment (X)',
    slug: 'fragment-x',
    reminderText: '(Cuando este Digimon fuera a ser borrado, descartando X de sus cartas de digievolución, no es borrado)',
    category: 'Activa Opcional',
    interruptive: 'Sí',
    area: 'Battle Area',
    debut: 'EX8',
    colors: 'Negro',
    summary:
      '⟨Fragment (X)⟩ es la última de las keywords interruptivas que tenemos. En este caso, si el Digimon con ⟨Fragment (X)⟩ va a ser destruido por cualquier motivo, descartando X sources cualesquiera de ese Digimon, se previene esa destrucción.',
    tips: [
      '⟨Fragment⟩ puede activarse para 0 DP, pero el Digimon va a seguir intentando ser destruido por tener 0 DP. Es posible activarlo varias veces para seguirte sacando sources hasta que no haya más o no quieras seguir activando ⟨Fragment⟩',
      '⟨Fragment⟩ va a triggerear todos los efectos de las sources descartas que sean “When effects trash this card from under 1 of your Digimon”, independientemente de si el Digimon bajo el que estaban sobrevive o no. Lo importante es que las sources queden en el trash, porque los efectos son de cada source.',
      'Si un Digimon va a ser destruido varias veces por el mismo efecto, puede activar ⟨Fragment⟩ una vez por cada instancia de destrucción, descartando la cantidad de sources correspondiente por cada instancia',
      'Aunque ⟨Fragment⟩ sea interruptiva, “When effects trash this card from under 1 of your Digimon” no lo es, así que esos efectos van a esperar que la acción que intentó destruir al Digimon termine, y respetará la prioridad de turno para activarse en caso de empatar con otro trigger',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 35,
  },
  {
    name: 'Execute',
    slug: 'execute',
    reminderText: '(Al final de tu turno, este Digimon puede atacar. Al final del ataque, borra a este Digimon. Los Digimon desuspendidos de tu oponente también pueden ser atacados con este efecto.)',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT21',
    colors: 'Violeta',
    summary:
      '⟨Execute⟩, la keyword del mazo de Violet Inboots de Digimon Liberator, le permite al Digimon atacar con el trigger [End of Turn], y gana el efecto “[End of Attack] Delete this Digimon”. Con este efecto también se pueden atacar a Digimon parados. ',
    tips: [
      'Si un Digimon ataca con ⟨Execute⟩, no se van a poder activar más instancias de ⟨Execute⟩ de otros Digimon, ya que todos los efectos [End of Turn] (tuyos y del oponente) deben activarse antes de Counter Timing.', 
      'Para atacar con ⟨Execute⟩ el Digimon debe poder atacar normalmente fuera de ⟨Execute⟩. Es decir, estar en el turno propio, no estar suspendido, no estar afectado por “can’t attack”, no haberse jugado ese turno sin tener ⟨Rush⟩ etc. ⟨Execute⟩ solo ignora la regla de no poder atacar a Digimon parados.',
      'Si un Digimon ataca con ⟨Execute⟩, sus [When Attacking] van a pasar a tener prioridad sobre el resto de los efectos [End of Turn], y va a tener que activarlos inmediatamente, incluyendo los efectos “when a Digimon attacks” del oponente',
      '⟨Execute⟩ no cuenta como suspenderse por efecto; la keyword te hizo atacar, y atacar es lo que te hizo suspenderte',
      '⟨Execute⟩ cuenta como destrucción por efecto propio',
      'Si el Digimon que atacó usando ⟨Execute⟩ deja de tener ⟨Execute⟩ antes de finalizar el ataque, igualmente se va a destruir, porque el efecto  “[End of Attack] Delete this Digimon” ya lo ganó',
      'Si el Digimon que atacó usando ⟨Execute⟩ tiene efectos [End of Attack], va a poder activarlos en cualquier orden junto con la destrucción con ⟨Execute⟩. Obviamente, si activa ⟨Execute⟩, ya no va a poder activar los demás. ',
      'Los [On Deletion] triggereados por la destrucción por ⟨Execute⟩ todavía cuentan como que se están resolviendo en medio de un ataque',
      'Como ⟨Execute⟩ es un efecto [End of Turn], si se gana ⟨Execute⟩ o se juega un Digimon con ⟨Execute⟩ posteriormente al trigger [End of Turn], ese Digimon no va a poder activarlo',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 36,
  },
  {
    name: 'Progress',
    slug: 'progress',
    reminderText: 'Mientras este Digimon ataca, no es afectado por efectos del oponente.',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT21',
    colors: 'Rojo',
    summary:
      'Otorga inmunidad a efectos del oponente durante todo el ataque del digimon con <Progress>.',
    tips: [
      '⟨Progress⟩ no tiene trigger ni activación, simplemente está activa mientras el Digimon la tenga durante su ataque. Si la gana a la mitad del ataque va a empezar a funcionar, y si la pierde va a dejar de funcionar',
      '“Estar atacando” engloba todo el proceso desde que el Digimon declara su ataque hasta que terminan de resolverse todos los efectos derivados del mismo, incluyendo terminar completamente los [End of Attack] y sus derivados. Básicamente, hasta que el jugador pueda tomar una nueva acción no relacionada con ese ataque, como, por ejemplo, atacar de nuevo. ',
      'Si el Digimon tenía efectos aplicados por el oponente o los gana durante el ataque, serán ignorados durante el ataque, y volverán a aplicarse una vez terminado el mismo',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 37,
  },
  {
    name: 'Link +X',
    slug: 'link-plus-x',
    reminderText: '(Suma X a la cantidad de Links máximos de este Digimon)',
    category: 'Pasiva',
    interruptive: 'No',
    area: 'Battle Area',
    debut: 'BT21',
    colors: 'Todos (Appmon)',
    summary:
      '⟨Link +X⟩ es una keyword exclusiva de los Digimon con trait Appmon, por ahora solo presente en los level 6, o “Gods”. Al ser 1 el Link máximo en todos los Digimon por defecto, ⟨Link +X⟩ le permite a un Digimon tener más de una carta linkeada a la vez. ',
    tips: [
      'Un Digimon con ⟨Link +X⟩ puede tener al mismo tiempo 1+X cartas linkeadas. Cuando un Digimon con más de una carta linkeada se intenta linkear una carta que lo haría superar su máximo de links, el jugador elige cuál carta linkeada descartar en su lugar ',
      'Si un Digimon deja de tener ⟨Link +X⟩, deben descartarse cartas linkeadas hasta dejar de pasarse del nuevo máximo de Link (por defecto, 1). Estas cartas son descartadas todas juntas en un Rule Check (no inmediatamente) y esto no cuenta como descartarlas por efecto. ',
      'Es posible tener linkeadas dos copias de la misma carta',
      'El orden de las cartas linkeadas es irrelevante',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 38,
  },
  {
    name: 'Training',
    slug: 'training',
    reminderText: '(Durante la Main Phase, suspendiendo a este Digimon, coloca la carta del tope de tu mazo boca abajo como la carta de digievolución del fondo de este Digimon. Este efecto puede también activarse en la Breeding Area.)',
    category: 'Activa Opcional',
    interruptive: 'No',
    area: 'Field / Breeding Area',
    debut: 'EX9',
    colors: 'Todos (DM)',
    summary:
      '⟨Training⟩ es la keyword más nueva hasta el momento, debutando en EX9 exclusivamente para los Digimon DM. Tiene la particularidad de ser la única keyword que funciona en la Breeding Area. Suspendiendo al Digimon, se coloca boca abajo la carta del tope del mazo como su source.',
    tips: [
      'Si el Digimon no puede suspenderse, no puede activarse ⟨Training⟩',
      'Si el Digimon se desuspende durante el turno, puede activarse ⟨Training⟩ más de una vez',
      'Las sources boca abajo solo pueden ser vistas por su dueño. Una vez que se van a una zona pública (por ejemplo, el trash) ahí las pueden ver ambos jugadores',
      'Si el jugador no tiene mazo, igualmente puede suspenderse por ⟨Training⟩ y no hacer nada',
      'Las sources boca abajo no tienen texto ni ninguna característica. Si son ACE, no hacen ⟨Overflow⟩, y si se convierten en la carta del tope de una pila, se descarta la pila',
    ],
    comparisons: [],
    funFact: '',
    sortOrder: 39,
  },
];

const needsReset = async () => {
  const currentRules = await PointRule.findAll({ order: [['sortOrder', 'ASC'], ['id', 'ASC']] });

  if (currentRules.length !== defaultRules.length) {
    return true;
  }

  return currentRules.some((rule) => !rule.label || !rule.placingFrom || !rule.placingTo);
};

export const seedPointRules = async () => {
  if (await needsReset()) {
    await PointRule.destroy({ where: {} });
    await PointRule.bulkCreate(defaultRules);
  }
};

export const seedSyncState = async () => {
  await SyncState.findOrCreate({
    where: { syncKey: 'catamarca' },
    defaults: {
      status: 'idle',
      message: 'Sin sincronizaciones todavía',
    },
  });
};

export const seedKeywords = async () => {
  await Keyword.bulkCreate(defaultKeywords, {
    updateOnDuplicate: [
      'name',
      'slug',
      'reminderText',
      'category',
      'interruptive',
      'area',
      'debut',
      'colors',
      'summary',
      'tips',
      'comparisons',
      'funFact',
      'sortOrder',
      'updatedAt',
    ],
  });
};