export const organizationRolePermissionsSeed = {
  owner: [
    'organizations.view',
    'organizations.update',
    'organization.members.manage',
    'organization.permissions.manage',
    'tournaments.view',
    'tournaments.create',
    'tournaments.edit_any',
    'tournaments.publish',
    'tournaments.delete',
    'registrations.manage',
    'checkin.manage',
    'rounds.manage',
    'matches.report',
    'standings.view',
    'decklists.view_private',
    'points.manage_org',
    'rankings.view',
  ],

  organization_admin: [
    'organizations.view',
    'organizations.update',
    'organization.members.manage',
    'tournaments.view',
    'tournaments.create',
    'tournaments.edit_any',
    'tournaments.publish',
    'registrations.manage',
    'checkin.manage',
    'rounds.manage',
    'matches.report',
    'standings.view',
    'decklists.view_private',
    'rankings.view',
  ],

  tournament_manager: [
    'organizations.view',
    'tournaments.view',
    'tournaments.create',
    'tournaments.edit_any',
    'tournaments.publish',
    'registrations.manage',
    'checkin.manage',
    'rounds.manage',
    'matches.report',
    'standings.view',
    'decklists.view_private',
    'rankings.view',
  ],

  tournament_staff: [
    'organizations.view',
    'tournaments.view',
    'registrations.manage',
    'checkin.manage',
    'matches.report',
    'standings.view',
    'rankings.view',
  ],

  viewer: [
    'organizations.view',
    'tournaments.view',
    'standings.view',
    'rankings.view',
  ],
};