export const rolePermissionsSeed = {
  system_owner: ['*'],

  platform_admin: [
    'users.view',
    'users.create',
    'users.update',
    'users.delete',
    'organization_requests.review',
    'organization_requests.create',
    'organizations.view',
    'organizations.create',
    'organizations.update',
    'tournaments.view',
    'registrations.create',
    'decklists.submit',
    'standings.view',
    'rankings.view',
    'points.manage_global',
  ],

  support_admin: [
    'users.view',
    'organization_requests.review',
    'organization_requests.create',
    'organizations.view',
    'tournaments.view',
    'registrations.create',
    'decklists.submit',
    'standings.view',
    'rankings.view',
  ],
  player: [
    'organization_requests.create',
    'organizations.view',
    'tournaments.view',
    'registrations.create',
    'decklists.submit',
    'standings.view',
    'rankings.view',
  ],
};